# Generated by Django 4.2.1 on 2023-06-01 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('release', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.filmcategory')),
            ],
        ),
    ]
