# Generated by Django 4.2.1 on 2023-06-01 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_film_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cinema.filmcategory'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='release',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
