# Generated by Django 4.2.1 on 2023-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_film_category_alter_film_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_empty',
            field=models.BooleanField(default=True),
        ),
    ]
