# Generated by Django 4.2.1 on 2023-06-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_film_is_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.filmcategory'),
        ),
    ]
