# Generated by Django 4.2.1 on 2023-06-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_hall_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
