# Generated by Django 4.2.1 on 2023-06-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_hall_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmcategory',
            name='number',
            field=models.IntegerField(default=18, unique=True),
            preserve_default=False,
        ),
    ]
