# Generated by Django 4.2.1 on 2023-06-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_filmcategory_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='unavailable_seats',
        ),
        migrations.AddField(
            model_name='session',
            name='is_seats_empty',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('seat_in_a_row', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.session')),
            ],
        ),
    ]
