# Generated by Django 4.2.1 on 2023-06-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_remove_session_unavailable_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
