# Generated by Django 4.2.1 on 2023-06-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_seat_is_available_delete_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmcategory',
            name='number',
            field=models.IntegerField(),
        ),
    ]
