# Generated by Django 4.2.1 on 2023-06-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='row',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_in_a_row',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seat'),
        ),
    ]
