# Generated by Django 4.2.1 on 2023-06-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_remove_ticket_row_remove_ticket_seat_in_a_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='sessions_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='total_tickets_sold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
