# Generated by Django 4.2.1 on 2023-06-03 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Формат номера телефона: +375 (29) XXXXXXX', regex='^\\+375 \\(29\\) \\d{7}}$')]),
        ),
    ]
